from django.urls import path
from . import views, AdminViews, StudentViews, TeacherViews, Api
urlpatterns = [
    # Login Path
    path('', views.home, name="home"),
    path('login', views.login, name="login"),
    path('index', views.index, name="index"),
    path('doLogin', views.doLogin, name="doLogin"),
    path('adminLogin', views.AdminLogin , name="adminLogin"),
    path('logout', views.logout , name="logout"),
    # Student Path
    path('student_home', StudentViews.student_home, name="student_home"),
    path('tkb',StudentViews.tkb, name="tkb"),
    path('search',StudentViews.search, name="search"),
    path("register_course", StudentViews.register, name="register_course"),
    path('doRegister/<str:course_id>/<str:class_id>',StudentViews.register_course, name="doRegister"),
    path('delCourse/<str:course_id>/<str:class_id>', StudentViews.delCourse, name="delCourse"),
    path("course", StudentViews.course, name="course"),
    path("result",StudentViews.result, name = "result"),
    path('content_student/<str:course_id>/<str:class_id>',StudentViews.content_student, name="content_student"),
    # Teacher Path 
    path('teacher_home', TeacherViews.teacher_home , name="teacher_home"),
    path('schedule', TeacherViews.schedule , name="schedule"),
    path('teacher_course', TeacherViews.course, name="teacher_course"),
    path('score',TeacherViews.score, name="score"),
    path('notification', TeacherViews.notification , name="notification"),
    path('notiList/<str:course_id>/<str:class_id>', TeacherViews.notiList, name="notiList"),
    path('studentList/<str:course_id>/<str:class_id>', TeacherViews.studentList, name="studentList"),
    path('scoring/<int:student_id>/<str:course_id>/<str:class_id>', TeacherViews.scoring, name="scoring"),
    path('content/<str:course_id>/<str:class_id>', TeacherViews.content, name="content"),
    path('upload/<str:course_id>/<str:class_id>/<str:subject>', TeacherViews.upload, name="upload"),
    path('delContent/<str:course_id>/<str:class_id>/<str:subject>/<int:index>/', TeacherViews.delContent ,name="delContent"),
    path('addsubject/<str:course_id>/<str:class_id>/',TeacherViews.addsubject, name="addsubject"),
    # Admin Path
    path('admin_home', AdminViews.home, name="admin_home"),
    path('student_view', AdminViews.student_view, name="student_views"),
    path('teacher_view', AdminViews.teacher_view, name="teacher_views"),
    path('course_view', AdminViews.course_view, name="course_views"),
    path('notification_view', AdminViews.notification_view, name="notification_views"),
    path('feedback_view', AdminViews.feedback_view, name="feedback_views"),
    path('stdifo/<int:id>',AdminViews.stdinfo , name="stdinfo"),
    path('editstd/<int:id>', AdminViews.editstd, name="editstd"),
    path('doEditStd/<int:id>' ,AdminViews.doEditStd , name="doEditStd"),
    path('addstd',AdminViews.addstd, name="addstd"),
    path('doADddStd', AdminViews.doAddStd, name="doAddStd"),
    path('addteacher', AdminViews.addteacher, name="addteacher"),
    path('teacherinfo/<int:id>', AdminViews.teacherinfo, name="teacherinfo"),
    path('doAddTeacher',AdminViews.doAddTeacher, name="doAddTeacher"),
    path('editTeacher/<int:id>', AdminViews.editTeacher, name="editTeacher"),
    path('doEditTeacher/<int:id>', AdminViews.doEditTeacher, name="doEditTeacher"),
    path('doDelStd/<int:id>',AdminViews.doDelStd, name="doDelStd"),
    path('doDelTeacher/<int:id>',AdminViews.doDelTeacher,name="doDelTeacher"),
    path('addcourse', AdminViews.addCourse, name='addcourse'),
    path('doAddCourse', AdminViews.doAddCourse, name="doAddCourse"),
    path('editCourse/<str:id>', AdminViews.editCourse, name="editCourse"),
    path('doEditCourse/<str:id>',AdminViews.doEditCourse, name="doEditCourse"),
    path('doDelCourse/<str:id>',AdminViews.doDelCourse, name="doDelCourse"),
    path('courseinfo/<str:course_id>',AdminViews.courseinfo , name="courseinfo"),
    path('courseinfo/<str:course_id>/addclass', AdminViews.addclass, name="addclass"),
    path('courseinfo/<str:course_id>/doAddClass' ,AdminViews.doAddClass, name="doAddClass"),
    path('doEditClass/<str:course_id>/<str:class_id>',AdminViews.doEditClass, name="doEditClass"),
    path('courseinfo/<str:course_id>/editClass/<str:class_id>', AdminViews.editClass, name="editClass"),
    path('courseinfo/<str:course_id>/doDelClass/<str:class_id>' ,AdminViews.doDelClass, name="doDelClass"),
    #API
    path('check_id',Api.check_id, name="check_id")
]